name: Bug Report
description: Report a bug to help us improve
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report

        Please fill out the information below to help us diagnose and address the issue.

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: When I do X, Y happens instead of Z.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: A step-by-step guide to reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: false

  - type: dropdown
    id: llm-type
    attributes:
      label: LLM Base
      description: Which Language Learning Model are you referring to?
      options:
        - GPT3.5
        - GPT4.0
        - Others
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      placeholder: e.g., 3.9.1
    validations:
      required: true

  - type: input
    id: os-system
    attributes:
      label: Operating System
      placeholder: e.g., Windows 10, macOS Big Sur, Ubuntu 20.04
    validations:
      required: true


  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

